"""Initial migration

Revision ID: 19ac2d1f6a3b
Revises: 13b613178fb8
Create Date: 2025-10-30 03:28:53.995023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ac2d1f6a3b'
down_revision = '13b613178fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pixel_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_domain', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pixel_setting', schema=None) as batch_op:
        batch_op.drop_column('allowed_domain')

    # ### end Alembic commands ###
